# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('favorites_total', models.IntegerField(default=0, verbose_name='favorites_totle')),
            ],
            options={
                'verbose_name_plural': 'article_info',
                'ordering': ['-favorites_total'],
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.Article')),
            ],
            options={
                'verbose_name_plural': 'favorites_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='username')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
            ],
            options={
                'verbose_name_plural': 'user_info',
                'ordering': ['-reg_time'],
            },
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='blog.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.User'),
        ),
    ]
